version: "3.8"

services:
  ente-server:
    image: enteio/server:latest
    container_name: ente-server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - ENTE_ADMIN_USERNAME=${ENTE_ADMIN_USERNAME}
      - ENTE_ADMIN_PASSWORD=${ENTE_ADMIN_PASSWORD}
      - ENTE_S3_BUCKET=${ENTE_S3_BUCKET}
      - ENTE_S3_ACCESS_KEY=${ENTE_S3_ACCESS_KEY}
      - ENTE_S3_SECRET_KEY=${ENTE_S3_SECRET_KEY}
      - ENTE_S3_ENDPOINT=http://minio:9000
      - ENTE_DATABASE_URL=postgres://ente:ente@postgres:5432/ente?sslmode=disable
    depends_on:
      - postgres
      - minio
    volumes:
      - ente-data:/data

  postgres:
    image: postgres:15-alpine
    container_name: ente-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ente
      - POSTGRES_PASSWORD=ente
      - POSTGRES_DB=ente
    volumes:
      - ente-postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio:RELEASE.2024-01-01T00-00-00Z
    container_name: ente-minio
    restart: unless-stopped
    environment:
      - MINIO_ROOT_USER=${ENTE_S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${ENTE_S3_SECRET_KEY}
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - ente-minio-data:/data

volumes:
  ente-data:
  ente-postgres-data:
  ente-minio-data:
